# version: "3.9"

# services:

#   postgres:
#     image: postgres:15
#     container_name: postgres_db
#     restart: always
#     environment:
#       POSTGRES_DB: pricing_model
#       POSTGRES_USER: viraj
#       POSTGRES_PASSWORD: viraj123
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

#   backend:
#     build: ./backend
#     container_name: django_backend
#     command: gunicorn backend.wsgi:application --bind 0.0.0.0:8001

#     volumes:
#       - ./backend:/app

#     ports:
#       - "8001:8001"

#     env_file:
#       - ./backend/.env   # ‚≠ê VERY IMPORTANT

#     depends_on:
#       - postgres
#       - redis


#   frontend:
#     build: ./frontend
#     container_name: angular_frontend
#     ports:
#       - "80:80"
#     depends_on:
#       - backend

#   redis:
#   image: redis:7
#   restart: always

#   celery:
#     build: ./backend
#     command: celery -A backend worker -l info
#     env_file:
#       - ./backend/.env
#     depends_on:
#       - postgres
#       - redis

# volumes:
#   postgres_data:

version: "3.9"

services:

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: pricing_model
      POSTGRES_USER: viraj
      POSTGRES_PASSWORD: viraj123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U viraj -d pricing_model"]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


  backend:
    build: ./backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - ./backend:/app
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always


  celery:
    build: ./backend
    command: celery -A backend worker -l info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always


  # OPTIONAL BUT HIGHLY RECOMMENDED
  # Scheduler for periodic tasks
  celery-beat:
    build: ./backend
    command: celery -A backend beat -l info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      redis:
        condition: service_healthy
    restart: always


  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always


volumes:
  postgres_data:
